name: CI Github Pages
on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install  ️ 
        run: cd package/plugin && pnpm install --no-frozen-lockfile
      - name: Build
        run: cd package/plugin && npm run build
    
      - name: Deploy 
        run: cd package/plugin && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}